// Auto-generated by make — do not edit
let buildVersion = "0.9.0"
let buildCommit = "62e2b70"
let buildBranch = "main"
let buildDate = "2026-04-06 22:35:34 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
