// Auto-generated by make — do not edit
let buildVersion = "1.1.1"
let buildCommit = "4e802f1"
let buildBranch = "main"
let buildDate = "2026-04-22 16:55:49 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
