// Auto-generated by make — do not edit
let buildVersion = "0.6.2"
let buildCommit = "a84ef38"
let buildBranch = "main"
let buildDate = "2026-03-31 09:05:15 UTC"
let buildSwiftVersion = "6.3"
let buildOS = "macOS 26.3.1"
